#!/bin/sh

message=$(cat $1)
pattern="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.+\))?: .{1,50}"

if ! echo "$message" | grep -iqE "$pattern"; then
  echo "❌ 커밋 메시지 컨벤션 오류: 커밋 메시지 확인해주세요." >&2
  exit 1
fi

