#!/bin/sh

message=$(cat $1)
pattern="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.+\))?: .{1,50}"

if ! echo "$message" | grep -iqE "$pattern"; then
  echo "Invalid commit message format" >&2
  exit 1
fi

